=== usernameAshu/Confluent-Kafka-Producer/src/main/resources/json/json_schema_lumen.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "messageId": {
      "type": "string"
    },
    "messageTime": {
      "type": "integer"
    },
    "messageType": {
      "type": "string"
    },
    "messageName": {
      "type": "string"
    },
    "responseName": {
      "type": "string"
    },
    "pattern": {
      "type": "string"
    },
    "version": {
      "type": "string"
    },
    "source": {
      "type": "string"
    },
    "uniqueId": {
      "type": "string"
    },
    "correlationId": {
      "type": "string"
    },
    "payload": {
      "type": "object"
    }
  },
  "required": [
    "messageId",
    "messageTime",
    "messageType",
    "messageName",
    "responseName",
    "pattern",
    "version",
    "source",
    "uniqueId",
    "correlationId",
    "payload"
  ]
}

=== usernameAshu/Confluent-Kafka-Producer/src/main/resources/json/payload_data/JobDetails.json
{
    "messageId": "2022-08-26 15:04:28.593:101872319",
    "messageTime": 1661506468593,
    "messageType": "PRIVATE",
    "messageName": "ODC.DEV.RTEST.SERVICEASSURANCE.TROUBLE.TESTING.JOBDETAILS.JSON.PRIVATE",
    "responseName": "",
    "pattern": "JSON",
    "version": "v1",
    "source": "rtest_dgw_rule_engine",
    "uniqueId": "",
    "correlationId": "101872319",
    "payload": {
        "jobDetails": {
            "priority": 5,
            "status": "Allocated",
            "reasonCode": null,
            "subReasonCode": null,
            "openDate": "07-JUL-2022 07:05:25.000000 AM",
            "id": "LMCOC021282501",
            "groupId": null,
            "groupParent": null,
            "alternateTrackingNumber": "0212825",
            "hostTrackingNumber": "C0212825",
            "businessUnit": "Residential",
            "dispatchInfo": {
                "dispatchType": "REPAIR",
                "duration": 4200,
                "dispatchCorrelationId": 101872319,
                "estimatedTimeOfArrival": "11-JUL-2022 08:00:00.000000 AM"
            },
            "appointment": {
                "appointmentStartDateTime": "11-JUL-2022 08:00:00.000000 AM",
                "appointmentEndDateTime": "11-JUL-2022 05:00:00.000000 PM",
                "dueDate": "11-JUL-2022 06:10:00.000000 PM",
                "accessAfterDateTime": "11-JUL-2022 08:00:00.000000 AM",
                "accessBeforeDateTime": "11-JUL-2022 09:10:00.000000 AM",
                "techName": "Mohammed Rahman",
                "statusComments": null,
                "appointmentOrderId": "RX34544986",
                "inquiryReservationNumber": "RXCORX34544986SQ002",
                "appointmentEarlyStartTime": "07-JUL-2022 08:00:00.000000 AM"
            },
            "taskInfo": null,
            "customerInfo": {
                "customerName": "HOLMAN, BRUCE J",
                "customerEmail": null,
                "accountNumber": null,
                "maintenancePlan": "N",
                "serviceClass": "Residential",
                "banBTN": null,
                "circuitId": "3034661237",
                "customerType": "Residential",
                "marketUnit": "RETAIL",
                "billingSystem": "CRIS",
                "purchaseOrderNumber": null,
                "primaryContactNumber": "9663569611",
                "secondaryContactName": null,
                "primaryContactName": null,
                "secondaryContactNumber": null
            },
            "location": {
                "city": "BROOMFIELD",
                "state": "CO",
                "zipCode": "80020",
                "district": "North Washington CO",
                "country": "US",
                "addressLine1": "340 CORAL ST, BROOM",
                "addressLine2": null,
                "accessCode": null,
                "geoLocation": {
                    "longitude": "-105.053381",
                    "latitude": "39.914754"
                },
                "region": "Denver Colorado",
                "propertyId": null,
                "area": "CO CRIS"
            },
            "productType": "VOICE",
            "orderType": "M",
            "installType": "NA",
            "repair": [
                {
                    "troubleType": "OOS",
                    "urlList": null
                }
            ],
            "feature": null,
            "remark": [
                {
                    "remark": "NDT CXX CHG APPT SUB: NDT CREATE FROM MICRO ARN101872319                                                                ldtst15",
                    "type": "TECHNICIAN_REMARKS",
                    "createDate": "09-JUL-2022 03:21:17.106507 AM"
                },
                {
                    "remark": "SINDHOOR RESCHEDUL",
                    "type": "ACCESS_REMARKS",
                    "createDate": "09-JUL-2022 03:21:17.108050 AM"
                },
                {
                    "remark": "MLT REQUEST CANCELED NDT-WFA",
                    "type": "SCREEN_NARR",
                    "createDate": "09-JUL-2022 03:21:17.108210 AM"
                },
                {
                    "remark": "Testing Docom notes from Micro",
                    "type": "ADDITIONAL_REMARKS",
                    "createDate": "09-JUL-2022 03:21:17.108319 AM"
                }
            ],
            "wireCenter": "BRFDCOMA",
            "technology": null,
            "downstreamRate": "0",
            "getQualificationResponse": {
                "overallStatusCode": "WORKED",
                "artisresponseHeader": null,
                "qualificationData": {
                    "tN": {
                        "lineNumber": "1237",
                        "nPA": "303",
                        "nXX": "466"
                    },
                    "requestType": "TN",
                    "network": "QWEST",
                    "svcAddress": {
                        "streetNumber": "340",
                        "streetName": "CORAL ST",
                        "city": "BROOMFIELD",
                        "stateProvince": "CO"
                    }
                }
            },
            "submarkets": null,
            "outageId": null,
            "switchgateActivationStatus": null,
            "relatedOrderId": null,
            "taskType": "VOXXXXXNDTBRP",
            "taskTypeDescription": "VOICE - OOS/No Dial Tone Biz Repair",
            "orderRepositoryServiceResponse": null,
            "relatedOrderIdInfo": null,
            "serviceOrderHistory": null,
            "projectName": null,
            "engineerName": null,
            "engineerNumber": null,
            "alternateCorrelationId": "0212825",
            "techId": "AD00671",
            "onhold": "N",
            "statusComments": null,
            "reassignCount": null,
            "aggregationId": null,
            "dispatchCompletionInfo": null,
            "associatedDispatches": null,
            "rontaId": null,
            "lmosDetails": {
                "wcNpaNxx": "303466",
                "handlingCode": "DSP",
                "istCode": "032",
                "routeCode": "994",
                "reportCategory": "CX",
                "testCode": "T1",
                "workPerformed": null,
                "screenResult": null,
                "handlingCodeDescription": null
            },
            "wfaDetails": null,
            "cktALocn": null,
            "cktZLocn": null,
            "jepCode": null,
            "jepCodeDesc": null,
            "custContFlag": null,
            "problem": null,
            "condition": null,
            "reason": null,
            "resolution": null,
            "missedCommitment": "N",
            "dispatchHistoryList": null,
            "selfAssignFlag": "N",
            "selfAssignTimestamp": null,
            "iwmpDetails": {
                "iwpInd": "N",
                "ticInd": "Y",
                "tripInd": "N"
            },
            "loopQualDropResponse": null,
            "techETAETRDetails": null,
            "tCompanyCode": "T600",
            "wireCenter8": "BRFDCOMA",
            "outageExclusionId": null,
            "isJobOnly": "N",
            "trunkGroupAccessCd": null,
            "cktAction": null,
            "originatingCenter": null,
            "reportCategory": null,
            "serviceAppointmentNumber": "SA-340521",
            "billingSystem": "CRIS",
            "dispatchSystem": "SFS",
            "originatingSystem": "LMOS",
            "serviceApptId": "08p560000006utrAAA",
            "workTypeName": "Voice Repair - Business",
            "workOrderId": "0WO5600000075MIGAY",
            "inJeopardy": "N",
            "troubleType": "OOS",
            "statusUpdateTimestamp": null,
            "hoursWorked": null,
            "jobsStatusHistory": [
                {
                    "priority": null,
                    "status": "Allocated",
                    "reasonCode": null,
                    "subReasonCode": null,
                    "openDate": null,
                    "id": null,
                    "groupId": null,
                    "groupParent": null,
                    "alternateTrackingNumber": null,
                    "hostTrackingNumber": null,
                    "businessUnit": null,
                    "dispatchInfo": null,
                    "appointment": null,
                    "taskInfo": null,
                    "customerInfo": null,
                    "location": null,
                    "productType": null,
                    "orderType": null,
                    "installType": null,
                    "repair": null,
                    "feature": null,
                    "remark": null,
                    "wireCenter": null,
                    "technology": null,
                    "downstreamRate": null,
                    "getQualificationResponse": null,
                    "submarkets": null,
                    "outageId": null,
                    "switchgateActivationStatus": null,
                    "relatedOrderId": null,
                    "taskType": null,
                    "taskTypeDescription": null,
                    "orderRepositoryServiceResponse": null,
                    "relatedOrderIdInfo": null,
                    "serviceOrderHistory": null,
                    "projectName": null,
                    "engineerName": null,
                    "engineerNumber": null,
                    "alternateCorrelationId": null,
                    "techId": null,
                    "onhold": null,
                    "statusComments": null,
                    "reassignCount": null,
                    "aggregationId": null,
                    "dispatchCompletionInfo": null,
                    "associatedDispatches": null,
                    "rontaId": null,
                    "lmosDetails": null,
                    "wfaDetails": null,
